require 'puppet_blacksmith/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
require 'puppetlabs_spec_helper/rake_tasks'

PuppetLint.configuration.fail_on_warnings = true
<% checks = @configs['default_disabled_lint_checks'] + ( @configs['extra_disabled_lint_checks'] || [] ) -%>
<% checks.each do |check| -%>
PuppetLint.configuration.send('<%= check %>')
<% end -%>
PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "pkg/**/*.pp"]

desc 'Generate pooler nodesets'
task :gen_nodeset do
  require 'beaker-hostgenerator'
  require 'securerandom'
  require 'fileutils'

  agent_target = ENV['TEST_TARGET']
  if agent_target
    master_target = ENV['MASTER_TEST_TARGET'] || 'redhat7-64mdcl'
    targets = "#{master_target}-#{agent_target}"
    cli = BeakerHostGenerator::CLI.new([targets])
    nodeset_dir = "tmp/nodesets"
    nodeset = "#{nodeset_dir}/#{targets}-#{SecureRandom.uuid}.yaml"
    FileUtils.mkdir_p(nodeset_dir)
    File.open(nodeset, 'w') do |fh|
      fh.print(cli.execute)
    end
    puts nodeset
  else
    puts "Please set the TEST_TARGET environment variable to use this task"
    exit 1
  end
end
